[package]
name = "easyadmin-skeleton"
version = "0.1.0"
authors = ["Default Name <email>"]
description = "A skeleton for easyadmin app written in rust."
edition = "2018"
license = "MIT"

[dependencies]
easyadmin = { version = "0.1.0", path = "../rust-easyadmin-framework/lib" }
rocket = "0.4.5"
rocket_contrib = "0.4.5"
diesel = { version = "1.4.5", features = ["mysql", "chrono"] }
r2d2-diesel = "1.0"
r2d2 = "0.8"

[[bin]]
name = "easyadmin-skeleton"
path = "bootstrap.rs"