version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 80:8000
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.32
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db-data:
